monitor = peripheral.wrap("top")
w,h = monitor.getSize()

monitor.setCursorPos(1,1)

x = 0

function printCentered(y,s)
    x = math.floor((w - string.len(s)) / 2 + 1)
    monitor.setCursorPos(x,y)
    monitor.clearLine()
    monitor.write(s)
end

monitor.setBackgroundColor(colors.white)
monitor.clear()
monitor.setTextColor(colors.black)
monitor.setTextScale(3)
printCentered(math.floor((h / 2) + 1), "########")
sleep(1)
printCentered(math.floor((h / 2) + 1), "########")
monitor.setTextColor(colors.red)
monitor.setCursorPos(x, math.floor((h / 2) + 1))
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
monitor.write("#")
sleep(1)
printCentered((math.floor(h / 2) + 1), "Done.")
sleep(1)
monitor.setBackgroundColor(colors.black)
monitor.clear()

